name: LifeSteal
author: ExperimentalX
main: me.experimental.LifeSteal
version: '${project.version}'
api-version: 1.19
commands:
   lsadmin:
      description: Administrator Commands
      usage: /lsadmin